##
## EPITECH PROJECT, 2020
## 109titration
## File description:
## Makefile
##

SRC	=	main.py	\

NAME	=	109titration

all:	$(NAME)

$(NAME):
	cp $(SRC) $(NAME)
	chmod +x $(NAME)

clean:
	rm $(NAME)

fclean:	clean

re:	fclean all

.PHONY:	all $(NAME) clean fclean re
